### ISSUE TITLE
[x11-misc/polybar] dependency font siji is missing

### ISSUE THREAD

**Issue by Dr-Terrible** [Dr-Terrible/ineluctable-overlay#17]
polybar-2.5 is missing a dependency, font-set [siji](https://github.com/stark/siji):

```shell
CMake Warning at cmake/utils.cmake:9 (message):
  Font not found: siji:pixelsize=10
```

**Comment by bpinto** [comment]
There are three fonts or font families queried during the build:

```
queryfont(FONT_FIXED ${FONT_FIXED} FIELDS family pixelsize)
queryfont(FONT_UNIFONT ${FONT_UNIFONT} FIELDS family fontformat)
queryfont(FONT_SIJI ${FONT_SIJI} FIELDS family pixelsize)
```

these are however optional fonts that are used in the example configuration:

```
optdepends = ttf-unifont: Font used in example 
optdepends = siji-git: Font used in example config
```

What is the proposed solution here? To use a custom USE flag to install these example fonts? I'm not sure if these are really a package dependency.

**Comment by bpinto** [comment]
Related issue https://github.com/jaagr/polybar/issues/407

**Comment by Dr-Terrible** [comment]
> What is the proposed solution here? To use a custom USE flag to install these example fonts? I'm not sure if these are really a package dependency.

Honestly, I have mixed feelings about adding `media-fonts/siji` and `media-fonts/unifont` as dependencies. They are clearly an `automagic dependency`, which is already a bad thing _per se_: https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies 

But I also understand why polybar is having issues with siji in the first place as reported by https://github.com/jaagr/polybar/issues/407: it's a `bitmap font-set`. Bitmap fonts don't play well when mixed together with `scaling font-sets` (TrueType, OpenType), leading to all sorts of glitches and graphical artefacts — especially with Wayland. That is exactly what is happening in https://github.com/jaagr/polybar/issues/407 and it's going to prevent a decent user experience when polybar is coupled with Sway.

I think I'm going to tag this issue report with a `wontfix` tag, unless in the next few days I came up with a good reason to add fonts as deps :disappointed: .

**Comment by Dr-Terrible** [comment]
Meanwhile, I packaged siji for the curios Gentooists: https://github.com/Dr-Terrible/fonts-overlay/commit/9b976127a30962476e8da82f13067ea5cec3b66d

**Comment by jaagr** [comment]
I agree with @Dr-Terrible on this. The reason I added the font querying to the build was because I got tons of report from people having `Wuncon Siji` and different unifont versions installed. The example config is what it is; an example. Will eventually drop Siji in favor of Font Awesome due to the availability.

**Comment by bpinto** [comment]
@Dr-Terrible should we tag this as wontfix and close this issue?
