### ISSUE TITLE
[x11-misc/polybar] failures on newest release

### ISSUE THREAD

**Issue by bpinto** [Dr-Terrible/ineluctable-overlay#23]
Hey @Dr-Terrible how are you doing? You've been away for a while!

Couldn't compile this latest version:

```
/var/tmp/portage/x11-misc/polybar-3.0.6_pre20171018/work/polybar-5737156ae5ea1b179032609dac29d3e60f0773c2/lib/i3ipcpp/src/ipc.cpp: In lambda function:
/var/tmp/portage/x11-misc/polybar-3.0.6_pre20171018/work/polybar-5737156ae5ea1b179032609dac29d3e60f0773c2/lib/i3ipcpp/src/ipc.cpp:25:17: error: ‘Reader’ is deprecated: Use CharReader and CharReaderBuilder instead [-Werror=deprecated-declarations]
   Json::Reader  reader; \
                 ^
/var/tmp/portage/x11-misc/polybar-3.0.6_pre20171018/work/polybar-5737156ae5ea1b179032609dac29d3e60f0773c2/lib/i3ipcpp/src/ipc.cpp:280:4: note: in expansion of macro ‘IPC_JSON_READ’
    IPC_JSON_READ(root);
    ^
In file included from /usr/include/jsoncpp/json/json.h:11:0,
                 from /var/tmp/portage/x11-misc/polybar-3.0.6_pre20171018/work/polybar-5737156ae5ea1b179032609dac29d3e60f0773c2/lib/i3ipcpp/src/ipc.cpp:6:
```

ideas?

**Comment by Dr-Terrible** [comment]
> Hey @Dr-Terrible how are you doing? You've been away for a while!

Hi bpinto! You're right, I was really busy with job lately, sorry for the long absence.
I'm back to my usual GitHub's routines. If in the future you need to contact me privately feel free to send me an email at toffanin.mauro@gmail.com ;)

p.s.: in the past months Gentoo Foundation introduced a lot of new stuff that break ton of things. I'm fixing them right now.

> Couldn't compile this latest version:

I can't reproduce the issue. On my machines the ebuild compiles fine.
What compiler are you using? And which USE flag are enable/disable?

**Comment by bpinto** [comment]
I have reinstalled my computer and will try to compile it again, but since I'm migrating to `sway` and there isn't a builtin compatibility with polybar yet, I am not going to use it for now.

I was using GCC 5.x and these custom package USE flags `x11-misc/polybar curl i3 network`.

P.S.: Awesome, I'm going to send you an email soon so we can keep in touch.

**Comment by Dr-Terrible** [comment]
> Update: Using i3 USE flag causes the build to fail.

Thank you, I'll give a try in a few minutes.

**Comment by Dr-Terrible** [comment]
>  fatal error: i3/ipc.h: No such file or directory

Even with your USE flags set up, I still got a successful compilation: https://pastebin.com/29krcP78
Here are my polybar's deps:

x11-wm/i3-4.13-r1 (stable version)
net-misc/curl-7.56.1 (stable version)
dev-util/cmake-3.8.2 (stable version)

What version of i3 are you using?
Try running the command: `qlist -e i3 | grep ipc\\.h`, it should give you: /usr/include/i3/ipc.h
If such file doesn't exist, then something funny is going on with your i3 installation.

**Comment by bpinto** [comment]
Currently I don't have i3 installed... so that must be it :man_facepalming: 

But I had on the previous install. Let's close this issue and I'll reopen in case I try i3 again. But I will probably migrate to another bar to use with sway.

**Comment by Dr-Terrible** [comment]
Oh well I'm an idiot, `x11-wm/i3` is never declared as a dep within polybar's ebuild. Ops, I missed that :D
