### ISSUE TITLE
repos.conf support

### ISSUE THREAD

**Issue by bpinto** [Dr-Terrible/ineluctable-overlay#5]
Instead of using layman (another dependency), I prefer to manage external overlays manually editing `repos.conf` myself.

There is however a dependency in a secondary overlay, dlang, for this overlay, is it necessary?

```
=== Sync completed for ineluctable-overlay
Unavailable repository 'dlang' referenced by masters entry in '/usr/local/overlay/ineluctable/metadata/layout.conf'
```

```
[ineluctable-overlay]
location = /usr/local/overlay/ineluctable
sync-type = git
sync-uri = https://github.com/Dr-Terrible/ineluctable-overlay.git
auto-sync = yes
```

**Comment by bpinto** [comment]
Great, thanks!

**Comment by Dr-Terrible** [comment]
> There is however a dependency in a secondary overlay, dlang, for this overlay, is it necessary?

You're right, the `dlang` repo is not more necessary; it was used by a specific ebuild which is not more part of this overlay. I'll remove the unnecessary reference, thank you for the report ;)
