### ISSUE TITLE
VTE ebuild not necessary

### ISSUE THREAD

**Issue by bpinto** [Dr-Terrible/ineluctable-overlay#6]
There is a newer VTE version on gentoo default overlay?

**Comment by Dr-Terrible** [comment]
Actually, that package is a VTE fork called [vte-ng](https://github.com/thestinger/vte-ng), and it's a runtime dependency for [termite](https://github.com/thestinger/termite) (a nice terminal for sway/i3/awesome window managers); unfortunately, upstream decided to maintain the name and API/ABI of the original VTE, so I had no other choice than to package it in the same way is the standard VTE library.

Is it causing conflicts, or symbols collisions, on your Gentoo set-ups? If yes, I can try to package VTE-ng as a slotted library to avoid them.

**Comment by bpinto** [comment]
I see, I thought it could be the case but I wasn't sure, I'm having this issue:

```
$ emerge --ask --changed-use --deep @world

These are the packages that would be merged, in order:

Calculating dependencies... done!

WARNING: One or more updates/rebuilds have been skipped due to a dependency conflict:

x11-libs/vte:2.91

  (x11-libs/vte-0.46.1:2.91/2.91::gentoo, ebuild scheduled for merge) conflicts with
    =x11-libs/vte-0.46.0-r666:2.91 required by (x11-terms/termite-12:0/0::ineluctable-overlay, installed)
    ^             ^^^^^^^^^^^     


Nothing to merge; quitting.
```

**Comment by Dr-Terrible** [comment]
That conflict is unfortunate; well then, a new slotted `x11-libs/vtg-ng` will be :)

It will take some time to complete the transition though, since I need to heavily patch the build scripts for `x11-terms/termite`.

**Comment by bpinto** [comment]
:sweat_smile: Thanks for the hard work!
